routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DevicesController;
use App\Http\Controllers\ReceiversController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('/dashboard/{device}/{type}', [DashboardController::class, 'type'])->name('dashboard.type');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('devices', DevicesController::class)->withTrashed();
    Route::resource('receivers', ReceiversController::class)->withTrashed();
});

require __DIR__.'/auth.php';

app/Models/Devices.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

use App\Models\Traits\RaidModel;

class Devices extends Model
{
    use HasFactory, SoftDeletes, RaidModel;

    protected $table = 'trans_devices';

    protected $fillable = [
        'name',
        'appid',
        'appsecret',
    ];

    public static function generateappid()
    {
        $result = '';
        $repeat = true;
        while ($repeat) {
            $result = strtoupper(Str::random(8));
            $record = self::where('appid', $result)->first();
            if (is_null($record)) {
                $repeat = false;
            }
        }

        return $result;
    }

    public static function generateappsecret()
    {
        $result = '';
        $repeat = true;
        while ($repeat) {
            $result = strtoupper(Str::random(16));
            $record = self::where('appsecret', $result)->first();
            if (is_null($record)) {
                $repeat = false;
            }
        }

        return $result;
    }

    public static function simpan($request)
    {
        $appid = self::generateappid();
        $appsecret = self::generateappsecret();
        $request = array_merge($request, [
            'appid'         => $appid,
            'appsecret'     => $appsecret
        ]);

        $record = new self;
        $record->fill($request);
        $record->save();

        return $record;
    }

    public function ubah($request)
    {
        $this->fill($request);
        $this->save();
    }
}

app/Http/Controllers/DevicesController.php
<?php

namespace App\Http\Controllers;

// ** utils
use Illuminate\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;

// ** requests
use App\Http\Requests\StoreDevicesRequest;
use App\Http\Requests\UpdateDevicesRequest;

// ** models
use App\Models\Devices;

class DevicesController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $user = Auth::user();

        return view('devices.index', [
            'title' => 'Devices',
            'isAllowCreate' => true,
            'records' => Devices::where('created_by', $user->id)
                                ->orderBy('id', 'desc')
                                ->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('devices.create', [
            'title' => 'Create New Device'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreDevicesRequest $request): RedirectResponse
    {
        $record = Devices::simpan($request->validated());
        return Redirect::route('devices.index')->with('status', 'record-created');
    }

    /**
     * Display the specified resource.
     */
    public function show(Devices $device): View
    {
        $user = Auth::user();
        if ($device->created_by !== $user->id) {
            abort(404);
        }

        return view('devices.show', [
            'title' => 'Show Device',
            'record' => $device
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Devices $device): View
    {
        $user = Auth::user();
        if ($device->created_by !== $user->id) {
            abort(404);
        }

        return view('devices.edit', [
            'title' => 'Edit Device',
            'record' => $device
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateDevicesRequest $request, Devices $device): RedirectResponse
    {
        $user = Auth::user();
        if ($device->created_by !== $user->id) {
            return Redirect::route('devices.index')->with('status', '404');
        }

        $device->ubah($request->validated());
        return Redirect::route('devices.index')->with('status', 'record-updated');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Devices $device)
    {
        $user = Auth::user();
        if ($device->created_by !== $user->id) {
            return response()->json([
                'status' => false,
                'message' => 'Data is not found.'
            ], 404);
        }

        $result = $device->delete();
        
        if ($result) {
            return response()->json([
                'status' => true,
                'message' => 'Data has been deleted.'
            ], 200);
        } else {
            return response()->json([
                'status' => false,
                'message' => 'Failed to delete data.'
            ], 400);
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/devices/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('devices.partials.header'))
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <form action="{{ route('devices.store') }}" method="post" class="grid grid-cols-1 gap-4">
                        @csrf
                        @method('post')

                        <div>
                            <x-input-label for="name" :value="__('Name')" />
                            <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" autocomplete="name" />
                            <x-input-error :messages="$errors->get('name')" class="mt-2" />
                        </div>

                        <div class="grid grid-cols-2 gap-2">
                            <a href="{{route('devices.index')}}" class="rounded bg-gray-500 hover:bg-gray-600 text-white text-center px-4 py-2" title="Back">
                                <i class="fa fa-chevron-left"></i>
                                {{ __('Back') }}
                            </a>

                            <button type="submit" class="rounded bg-green-500 hover:bg-green-600 text-white text-center px-4 py-2" title="Save">
                                <i class="fa fa-save"></i>
                                {{ __('Save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/devices/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('devices.partials.header'))
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <form action="{{ route('devices.update', $record->id) }}" method="post" class="grid grid-cols-1 gap-4">
                        @csrf
                        @method('put')

                        <div>
                            <x-input-label for="name" :value="__('Name')" />
                            <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" autocomplete="name" value="{{ $record->name }}" />
                            <x-input-error :messages="$errors->get('name')" class="mt-2" />
                        </div>

                        <div class="grid grid-cols-2 gap-2">
                            <a href="{{route('devices.index')}}" class="rounded bg-gray-500 hover:bg-gray-600 text-white text-center px-4 py-2" title="Back">
                                <i class="fa fa-chevron-left"></i>
                                {{ __('Back') }}
                            </a>

                            <button type="submit" class="rounded bg-green-500 hover:bg-green-600 text-white text-center px-4 py-2" title="Save">
                                <i class="fa fa-save"></i>
                                {{ __('Update') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/devices/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('devices.partials.header'))
        </div>
    </x-slot>
    @if (in_array(session('status'), ['record-created', 'record-updated', 'record-deleted']))
        <div 
            x-data="{ show: true }"
            x-show="show"
            x-transition
            x-init="setTimeout(() => show = false, 3000)"
            class="flex items-center bg-green-500 text-white text-sm font-bold p-4" 
            role="alert">
            <p>
                <i class="fa fa-check-circle"></i>
                @if (session('status') == 'record-created')
                    {{ __('New data has been saved.') }}
                @elseif (session('status') == 'record-updated')
                    {{ __('Data has been updated.') }}
                @elseif (session('status') == 'record-deleted')
                    {{ __('Data has been deleted.') }}
                @endif
            </p>
        </div>
    @elseif (in_array(session('status'), ['404']))
        <div 
            x-data="{ show: true }"
            x-show="show"
            x-transition
            x-init="setTimeout(() => show = false, 3000)"
            class="flex items-center bg-red-500 text-white text-sm font-bold p-4" 
            role="alert">
            <p>
                <i class="fa fa-times-circle"></i>
                @if (session('status') == '404')
                    {{ __('Data is not found.') }}
                @endif
            </p>
        </div>
    @endif

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    @include(('devices.partials.table'))
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/devices/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('devices.partials.header'))
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <div class="grid grid-cols-1 gap-4">
                        <div>
                            <x-input-label for="name" :value="__('Name')" />
                            <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" value="{{ $record->name }}" readonly />
                        </div>

                        <div>
                            <x-input-label for="appid" :value="__('APPID')" />
                            <x-text-input id="appid" name="appid" type="text" class="mt-1 block w-full" value="{{ $record->appid }}" readonly />
                        </div>

                        <div>
                            <x-input-label for="appsecret" :value="__('APPSECRET')" />
                            <x-text-input id="appsecret" name="appsecret" type="text" class="mt-1 block w-full" value="{{ $record->appsecret }}" readonly />
                        </div>

                        <div class="grid grid-cols-2 gap-2">
                            <a href="{{route('devices.index')}}" class="rounded bg-gray-500 hover:bg-gray-600 text-white text-center px-4 py-2" title="Back">
                                <i class="fa fa-chevron-left"></i>
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>