routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DevicesController;
use App\Http\Controllers\ReceiversController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('/dashboard/{device}/{type}', [DashboardController::class, 'type'])->name('dashboard.type');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('devices', DevicesController::class)->withTrashed();
    Route::resource('receivers', ReceiversController::class)->withTrashed();
});

require __DIR__.'/auth.php';

app/Models/Receivers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Receivers extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'trans_receivers';

    protected $fillable = [
        'device_id',
        'type',
        'body',
    ];

    public function device(): BelongsTo
    {
        return $this->belongsTo(Devices::class, 'device_id');
    }

    public static function simpan($request)
    {
        $record = new self;
        $record->fill($request);
        $record->save();

        return $record;
    }

    public function ubah($request)
    {
        $this->fill($request);
        $this->save();
    }
}

app/Http/Controllers/API/ReceiversController.php
<?php

namespace App\Http\Controllers\API;

// ** utils
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

// ** models
use App\Models\Devices;
use App\Models\Receivers;

class ReceiversController extends Controller
{
    public function sensor(Request $request)
    {
        $appid = $request->header('appid', '');
        $appsecret = $request->header('appsecret', '');
        $body = $request->all();

        $device = Devices::where('appid', $appid)
                         ->where('appsecret', $appsecret)
                         ->whereNull('deleted_at')
                         ->first();

        if ($device) {
            $data = [
                'device_id' => $device->id,
                'type'      => 'sensor',
                'body'      => json_encode($body)
            ];

            $record = Receivers::simpan($data);

            return response()->json([
                'status' => true,
                'message' => 'Data has been received.',
                'body' => $body
            ], 200);
        }

        return response()->json([
            'status' => false,
            'message' => 'Forbidden.'
        ], 403);
    }

    public function webhook($appid = '', $appsecret = '', Request $request)
    {
        $body = $request->all();

        $device = Devices::where('appid', $appid)
                         ->where('appsecret', $appsecret)
                         ->whereNull('deleted_at')
                         ->first();

        if ($device) {
            $data = [
                'device_id' => $device->id,
                'type'      => 'sensor',
                'body'      => json_encode($body)
            ];

            $record = Receivers::simpan($data);

            return response()->json([
                'status' => true,
                'message' => 'Data has been received.',
                'body' => $body
            ], 200);
        }

        return response()->json([
            'status' => false,
            'message' => 'Forbidden.'
        ], 403);
    }
}

app/Http/Controllers/ReceiversController.php
<?php

namespace App\Http\Controllers;

// ** utils
use Illuminate\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;

// ** requests
use App\Http\Requests\StoreReceiversRequest;
use App\Http\Requests\UpdateReceiversRequest;

// ** models
use App\Models\Devices;
use App\Models\Receivers;

class ReceiversController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $user = Auth::user();

        return view('receivers.index', [
            'title' => 'Receivers',
            'isAllowCreate' => true,
            'records' => Receivers::whereHas('device', function($q) use ($user) {
                                      $q->where('created_by', $user->id);
                                  })
                                  ->orderBy('id', 'desc')
                                  ->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $user = Auth::user();

        return view('receivers.create', [
            'title' => 'Create New Receiver',
            'devices' => Devices::where('created_by', $user->id)->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreReceiversRequest $request): RedirectResponse
    {
        $record = Receivers::simpan($request->validated());
        return Redirect::route('receivers.index')->with('status', 'record-created');
    }

    /**
     * Display the specified resource.
     */
    public function show(Receivers $receiver): View
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            abort(404);
        }

        return view('receivers.show', [
            'title' => 'Show Receiver',
            'record' => $receiver,
            'devices' => Devices::where('created_by', $user->id)->get()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Receivers $receiver): View
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            abort(404);
        }

        return view('receivers.edit', [
            'title' => 'Edit Receiver',
            'record' => $receiver,
            'devices' => Devices::where('created_by', $user->id)->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateReceiversRequest $request, Receivers $receiver): RedirectResponse
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            return Redirect::route('receivers.index')->with('status', '404');
        }

        $receiver->ubah($request->validated());
        return Redirect::route('receivers.index')->with('status', 'record-updated');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Receivers $receiver)
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            return response()->json([
                'status' => false,
                'message' => 'Data is not found.'
            ], 404);
        }

        $result = $receiver->delete();
        
        if ($result) {
            return response()->json([
                'status' => true,
                'message' => 'Data has been deleted.'
            ], 200);
        } else {
            return response()->json([
                'status' => false,
                'message' => 'Failed to delete data.'
            ], 400);
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/receivers/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('receivers.partials.header'))
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <form action="{{ route('receivers.store') }}" method="post" class="grid grid-cols-1 gap-4">
                        @csrf
                        @method('post')

                        <div>
                            <x-input-label for="device_id" :value="__('Device')" />
                            <x-select name="device_id" id="device_id" class="mt-1 block w-full">
                                <option value="">Select Device</option>
                                @foreach ($devices as $device)
                                    <option value="{{ $device->id }}">{{ $device->name }}</option>
                                @endforeach
                            </x-select>
                            <x-input-error :messages="$errors->get('device_id')" class="mt-2" />
                        </div>

                        <div>
                            <x-input-label for="type" :value="__('Type')" />
                            <x-select name="type" id="type" class="mt-1 block w-full">
                                <option value="">Select Type</option>
                                <option value="sensor">Sensor</option>
                            </x-select>
                            <x-input-error :messages="$errors->get('type')" class="mt-2" />
                        </div>

                        <div>
                            <x-input-label for="name" :value="__('Body')" />
                            <x-textarea name="body" id="body" class="mt-1 block w-full resize-none"></x-textarea>
                            <x-input-error :messages="$errors->get('body')" class="mt-2" />
                        </div>

                        <div class="grid grid-cols-2 gap-2">
                            <a href="{{route('receivers.index')}}" class="rounded bg-gray-500 hover:bg-gray-600 text-white text-center px-4 py-2" title="Back">
                                <i class="fa fa-chevron-left"></i>
                                {{ __('Back') }}
                            </a>

                            <button type="submit" class="rounded bg-green-500 hover:bg-green-600 text-white text-center px-4 py-2" title="Save">
                                <i class="fa fa-save"></i>
                                {{ __('Save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/receivers/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('receivers.partials.header'))
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <form action="{{ route('receivers.update', $record->id) }}" method="post" class="grid grid-cols-1 gap-4">
                        @csrf
                        @method('put')

                        <div>
                            <x-input-label for="device_id" :value="__('Device')" />
                            <x-select name="device_id" id="device_id" class="mt-1 block w-full">
                                <option value="">Select Device</option>
                                @foreach ($devices as $device)
                                    <option value="{{ $device->id }}" @if($record->device_id == $device->id) selected @endif>{{ $device->name }}</option>
                                @endforeach
                            </x-select>
                            <x-input-error :messages="$errors->get('device_id')" class="mt-2" />
                        </div>

                        <div>
                            <x-input-label for="type" :value="__('Type')" />
                            <x-select name="type" id="type" class="mt-1 block w-full">
                                <option value="">Select Type</option>
                                <option value="sensor" @if($record->type == 'sensor') selected @endif>Sensor</option>
                            </x-select>
                            <x-input-error :messages="$errors->get('type')" class="mt-2" />
                        </div>

                        <div>
                            <x-input-label for="name" :value="__('Body')" />
                            <x-textarea name="body" id="body" class="mt-1 block w-full resize-none">{{$record->body}}</x-textarea>
                            <x-input-error :messages="$errors->get('body')" class="mt-2" />
                        </div>

                        <div class="grid grid-cols-2 gap-2">
                            <a href="{{route('receivers.index')}}" class="rounded bg-gray-500 hover:bg-gray-600 text-white text-center px-4 py-2" title="Back">
                                <i class="fa fa-chevron-left"></i>
                                {{ __('Back') }}
                            </a>

                            <button type="submit" class="rounded bg-green-500 hover:bg-green-600 text-white text-center px-4 py-2" title="Save">
                                <i class="fa fa-save"></i>
                                {{ __('Update') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/receivers/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('receivers.partials.header'))
        </div>
    </x-slot>
    @if (in_array(session('status'), ['record-created', 'record-updated', 'record-deleted']))
        <div 
            x-data="{ show: true }"
            x-show="show"
            x-transition
            x-init="setTimeout(() => show = false, 3000)"
            class="flex items-center bg-green-500 text-white text-sm font-bold p-4" 
            role="alert">
            <p>
                <i class="fa fa-check-circle"></i>
                @if (session('status') == 'record-created')
                    {{ __('New data has been saved.') }}
                @elseif (session('status') == 'record-updated')
                    {{ __('Data has been updated.') }}
                @elseif (session('status') == 'record-deleted')
                    {{ __('Data has been deleted.') }}
                @endif
            </p>
        </div>
    @elseif (in_array(session('status'), ['404']))
        <div 
            x-data="{ show: true }"
            x-show="show"
            x-transition
            x-init="setTimeout(() => show = false, 3000)"
            class="flex items-center bg-red-500 text-white text-sm font-bold p-4" 
            role="alert">
            <p>
                <i class="fa fa-times-circle"></i>
                @if (session('status') == '404')
                    {{ __('Data is not found.') }}
                @endif
            </p>
        </div>
    @endif

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    @include(('receivers.partials.table'))
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/receivers/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row items-center">
            @include(('receivers.partials.header'))
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-2xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <div class="grid grid-cols-1 gap-4">
                        <div>
                            <x-input-label for="device_id" :value="__('Device')" />
                            <x-select name="device_id" id="device_id" class="mt-1 block w-full" disabled>
                                <option value="">Select Device</option>
                                @foreach ($devices as $device)
                                    <option value="{{ $device->id }}" @if($record->device_id == $device->id) selected @endif>{{ $device->name }}</option>
                                @endforeach
                            </x-select>
                        </div>

                        <div>
                            <x-input-label for="type" :value="__('Type')" />
                            <x-select name="type" id="type" class="mt-1 block w-full" disabled>
                                <option value="">Select Type</option>
                                <option value="sensor" @if($record->type == 'sensor') selected @endif>Sensor</option>
                            </x-select>
                        </div>

                        <div>
                            <x-input-label for="name" :value="__('Body')" />
                            <x-textarea name="body" id="body" class="mt-1 block w-full resize-none" readonly>{{$record->body}}</x-textarea>
                        </div>

                        <div class="grid grid-cols-2 gap-2">
                            <a href="{{route('receivers.index')}}" class="rounded bg-gray-500 hover:bg-gray-600 text-white text-center px-4 py-2" title="Back">
                                <i class="fa fa-chevron-left"></i>
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>