routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DevicesController;
use App\Http\Controllers\ReceiversController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('/dashboard/{device}/{type}', [DashboardController::class, 'type'])->name('dashboard.type');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('devices', DevicesController::class)->withTrashed();
    Route::resource('receivers', ReceiversController::class)->withTrashed();
});

require __DIR__.'/auth.php';

app/Models/Receivers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Receivers extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'trans_receivers';

    protected $fillable = [
        'device_id',
        'type',
        'body',
    ];

    public function device(): BelongsTo
    {
        return $this->belongsTo(Devices::class, 'device_id');
    }

    public static function simpan($request)
    {
        $record = new self;
        $record->fill($request);
        $record->save();

        return $record;
    }

    public function ubah($request)
    {
        $this->fill($request);
        $this->save();
    }
}

app/Http/Controllers/API/ReceiversController.php
<?php

namespace App\Http\Controllers\API;

// ** utils
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

// ** models
use App\Models\Devices;
use App\Models\Receivers;

class ReceiversController extends Controller
{
    public function sensor(Request $request)
    {
        $appid = $request->header('appid', '');
        $appsecret = $request->header('appsecret', '');
        $body = $request->all();

        $device = Devices::where('appid', $appid)
                         ->where('appsecret', $appsecret)
                         ->whereNull('deleted_at')
                         ->first();

        if ($device) {
            $data = [
                'device_id' => $device->id,
                'type'      => 'sensor',
                'body'      => json_encode($body)
            ];

            $record = Receivers::simpan($data);

            return response()->json([
                'status' => true,
                'message' => 'Data has been received.',
                'body' => $body
            ], 200);
        }

        return response()->json([
            'status' => false,
            'message' => 'Forbidden.'
        ], 403);
    }

    public function webhook($appid = '', $appsecret = '', Request $request)
    {
        $body = $request->all();

        $device = Devices::where('appid', $appid)
                         ->where('appsecret', $appsecret)
                         ->whereNull('deleted_at')
                         ->first();

        if ($device) {
            $data = [
                'device_id' => $device->id,
                'type'      => 'sensor',
                'body'      => json_encode($body)
            ];

            $record = Receivers::simpan($data);

            return response()->json([
                'status' => true,
                'message' => 'Data has been received.',
                'body' => $body
            ], 200);
        }

        return response()->json([
            'status' => false,
            'message' => 'Forbidden.'
        ], 403);
    }
}

app/Http/Controllers/ReceiversController.php
<?php

namespace App\Http\Controllers;

// ** utils
use Illuminate\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;

// ** requests
use App\Http\Requests\StoreReceiversRequest;
use App\Http\Requests\UpdateReceiversRequest;

// ** models
use App\Models\Devices;
use App\Models\Receivers;

class ReceiversController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $user = Auth::user();

        return view('receivers.index', [
            'title' => 'Receivers',
            'isAllowCreate' => true,
            'records' => Receivers::whereHas('device', function($q) use ($user) {
                                      $q->where('created_by', $user->id);
                                  })
                                  ->orderBy('id', 'desc')
                                  ->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $user = Auth::user();

        return view('receivers.create', [
            'title' => 'Create New Receiver',
            'devices' => Devices::where('created_by', $user->id)->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreReceiversRequest $request): RedirectResponse
    {
        $record = Receivers::simpan($request->validated());
        return Redirect::route('receivers.index')->with('status', 'record-created');
    }

    /**
     * Display the specified resource.
     */
    public function show(Receivers $receiver): View
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            abort(404);
        }

        return view('receivers.show', [
            'title' => 'Show Receiver',
            'record' => $receiver,
            'devices' => Devices::where('created_by', $user->id)->get()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Receivers $receiver): View
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            abort(404);
        }

        return view('receivers.edit', [
            'title' => 'Edit Receiver',
            'record' => $receiver,
            'devices' => Devices::where('created_by', $user->id)->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateReceiversRequest $request, Receivers $receiver): RedirectResponse
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            return Redirect::route('receivers.index')->with('status', '404');
        }

        $receiver->ubah($request->validated());
        return Redirect::route('receivers.index')->with('status', 'record-updated');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Receivers $receiver)
    {
        $user = Auth::user();
        if ($receiver->device->created_by !== $user->id) {
            return response()->json([
                'status' => false,
                'message' => 'Data is not found.'
            ], 404);
        }

        $result = $receiver->delete();
        
        if ($result) {
            return response()->json([
                'status' => true,
                'message' => 'Data has been deleted.'
            ], 200);
        } else {
            return response()->json([
                'status' => false,
                'message' => 'Failed to delete data.'
            ], 400);
        }
    }
}

resources/views/receivers/partials/header.blade.php
<h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight basis-10/12">
    {{ $title }}
</h2>
@if (isset($isAllowCreate) && $isAllowCreate)
    <a href="{{route('receivers.create')}}" class="rounded bg-green-500 hover:bg-green-600 text-white text-center px-4 py-2 basis-2/12" title="Add">
        <i class="fa fa-plus"></i>
        {{ __('New Data') }}
    </a>
@endif

resources/views/receivers/partials/table.blade.php
<table class="table-auto w-full border">
    <thead>
        <tr>
            <th class="border py-2">No</th>
            <th class="border py-2">Device</th>
            <th class="border py-2">Type</th>
            <th class="border py-2">Body</th>
            <th class="border py-2">Action</th>
        </tr>
    </thead>
    <tbody>
        @php $i = 1; @endphp
        @forelse ($records as $record)    
            <tr>
                <td class="border py-2 px-2 text-center w-1/12">{{ $i }}</td>
                <td class="border py-2 px-2">
                    <a href="{{ route('devices.show', $record->device->id) }}">{{ $record->device->name }} <i class="fa fa-up-right-from-square"></i></a>
                </td>
                <td class="border py-2 px-2">{{ $record->type }}</td>
                <td class="border py-2 px-2">{{ $record->body }}</td>
                <td class="border py-2 px-2 text-center w-2/12">
                    <button type="button" class="rounded bg-slate-500 hover:bg-slate-600 text-white px-2" title="Show" onclick="window.open(`{{ route('receivers.show', $record->id) }}`, `_self`)">
                        <i class="fa fa-eye"></i>
                    </button>
                    <button type="button" class="rounded bg-blue-500 hover:bg-blue-600 text-white px-2" title="Edit" onclick="window.open(`{{ route('receivers.edit', $record->id) }}`, `_self`)">
                        <i class="fa fa-pencil"></i>
                    </button>
                    <button type="button" class="rounded bg-red-500 hover:bg-red-600 text-white px-2" title="Delete" onclick="handleDelete({{ $record->id }})">
                        <i class="fa fa-trash"></i>
                    </button>
                </td>
            </tr>
            @php $i++; @endphp
        @empty
            <tr>
                <td colspan="99" class="text-center italic py-4">No Data</td>
            </tr>
        @endforelse
    </tbody>
</table>

<script>
    const handleDelete = (id) => {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            focusCancel: true,
            reverseButtons: true,
            showCancelButton: true,
            confirmButtonColor: '#EF4444',
            cancelButtonColor: '#64748B',
            confirmButtonText: 'Delete',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                axios.delete(`/receivers/${id}`)
                .then((res) => {
                    if (res.data.status) {
                        Swal.fire({
                            title: 'Success',
                            text: res.data.message,
                            icon: 'success',
                            showConfirmButton: false,
                            timer: 3000
                        }).then(() => {
                            window.location.reload();
                        });
                    }
                })
                .catch((err) => {
                    Swal.fire({
                        title: `${err.response.status} | ${err.response.statusText}`,
                        text: err.message,
                        icon: 'error',
                        showConfirmButton: false,
                        timer: 3000
                    })
                });
            }
        });
    }
</script>